\documentclass{article}

<<load_packages, include=FALSE>>=
library("xtable")
@


\begin{document}

\section{First Heading}

This is our first knitr document.

<<echo=TRUE, results='markup'>>=
x <- 1:10
plot(x)
print(x)
@

<<echo=TRUE, results='asis'>>=
x <- 1:10
plot(x)
print(x)
@

% A latex comment

<<init, include=FALSE>>=
## from now on no echo
opts_chunk$set(echo = FALSE)
@

% For tables uses results = "asis"
<<create_table, results='asis'>>=
TAB <- table(x)
xtable(TAB)
@



\end{document}